services:
    web:
        build:
            context: ./Web/app
            dockerfile: Dockerfile
            platforms:
                - "linux/amd64"
            tags:
                - "capstone/web:0.0.0"

        container_name: capstone_app

        ports:
            - "6969:6969"

        restart: on-failure

        healthcheck:
            test: [ "CMD-SHELL", "curl --silent --fail localhost:6969/demo_api_2/health-check || exit 1" ]
            interval: 5m
            timeout: 3s
            retries: 3

        deploy:
            mode: global

            restart_policy:
                condition: on-failure
                delay: 5s
                window: 120s
                max_attempts: 3

            resources:
                limits:
                    cpus: "4"
                    memory: 2048M
                reservations:
                    cpus: "1"
                    memory: 512M

    model:
        build:
            context: ./AI
            dockerfile: Dockerfile
            platforms:
                - "linux/amd64"
            tags:
                - "capstone/model:0.0.0"

        container_name: capstone_model

        ports:
            - "6968:6968"

        restart: on-failure

        healthcheck:
            test: ["CMD-SHELL", "curl --silent --fail localhost:6968/health-check || exit 1"]
            interval: 5m
            timeout: 3s
            retries: 3

        deploy:
            mode: global

            restart_policy:
                condition: on-failure
                delay: 5s
                window: 120s
                max_attempts: 3

            resources:
                limits:
                    cpus: "4"
                    memory: 8192M
                reservations:
                    cpus: "1"
                    memory: 512M
                    devices:
                        - capabilities: ["gpu"]
                          device_ids: ["all"]

#    nginx:
#        image: nginx:latest
#        build: nginx
#        restart: always
#        volumes:
#            - ./nginx:/etc/nginx/user_conf.d:ro
#        ports:
#            - "80:80"
#        depends_on:
#            - app
