services:
    ai:
        build:
            context: ./AI
            dockerfile: Dockerfile
            platforms:
                - "linux/amd64"
            tags:
                - "capstone/ai:3d"

        container_name: capstone_ai_3d

        ports:
            - "6970:6970"

        restart: on-failure

        healthcheck:
            test: [ "CMD-SHELL", "curl --silent --fail http://0.0.0.0:6970/ || exit 1" ]
            interval: 5m
            timeout: 3s
            retries: 3

        volumes:
            - ~/AI_web_data/AI/weight/:/weight

        environment:
            DEVICE: "cuda"
            CONFIG_PATH: "/weight/teacher/input_3d/config.json"
            WEIGHT_PATH: "/weight/teacher/input_3d/best_epoch20_step4519.pt"
            PORT: 6970

        networks:
            - web

        deploy:
            mode: global
            restart_policy:
                condition: on-failure
                delay: 5s
                window: 120s
                max_attempts: 3
            resources:
                limits:
                    cpus: "4"
                    memory: 8192M
                reservations:
                    cpus: "1"
                    memory: 1024M
                    devices:
                        -   capabilities: [ "gpu" ]
                            device_ids: [ "all" ]

    backend:
        build:
            context: ./Web/src/be
            dockerfile: Dockerfile
            platforms:
                - "linux/amd64"
            tags:
                - "capstone/be:3d"

        container_name: capstone_be_3d

        ports:
            - "6971:6971"

        volumes:
            - ~/AI_web_data/BE/input_3d/run_results/plots:/run_results/plots
            - ~/AI_web_data/BE/input_3d/run_results/scores:/run_results/scores
            - ~/AI_web_data/BE/input_3d/run_results/videos:/run_results/videos
        
        environment:
            WINDOW_LENGTH: 15
            POLYORDER: 6

            HEIGHT: 0.9
            THRESHOLD: null
            DISTANCE: null
            PROMINENCE: 0.00001
            WIDTH: 3
            WLEN: null
            REL_HEIGHT: 0.8
            PLATEAU_SIZE: null

            MERGE_GAP: 5

            TMP_DIR: "run_results"
            VAD_ENDPOINT: "http://capstone_ai_3d:6970"
            PORT: 6971

        restart: on-failure

        healthcheck:
            test: ["CMD", "curl", "-f", "http://0.0.0.0:6971/health"]
            interval: 30s
            timeout: 10s
            retries: 3
            start_period: 15s

        networks:
            - web

        deploy:
            mode: global
            restart_policy:
                condition: on-failure
                delay: 5s
                window: 120s
                max_attempts: 3
            resources:
                limits:
                    cpus: "4"
                    memory: 4096M
                reservations:
                    cpus: "2"
                    memory: 2048M

    frontend:
        build:
            context: ./Web/src/fe
            dockerfile: Dockerfile
            platforms:
                - "linux/amd64"
            tags:
                - "capstone/fe:3d"

        container_name: capstone_fe_3d

        ports:
            - "6972:6972"

        environment:
            VITE_API_URL: "http://0.0.0.0:6971/"
            VITE_PORT: 6972

        depends_on:
            - backend

        restart: on-failure

        healthcheck:
            test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://0.0.0.0:6972/"]
            interval: 30s
            timeout: 5s
            retries: 3
            start_period: 5s

        networks:
            - web

        deploy:
            mode: global
            restart_policy:
                condition: on-failure
                delay: 5s
                window: 120s
                max_attempts: 3
            resources:
                limits:
                    cpus: "4"
                    memory: 4096M
                reservations:
                    cpus: "2"
                    memory: 2048M

networks:
  web:
    driver: bridge
