services:
    ai:
        build:
            context: ./AI
            dockerfile: Dockerfile
            platforms:
                - "linux/amd64"
            tags:
                - "capstone/ai:mixed"

        container_name: capstone_ai_mixed

        ports:
            - "6973:6973"

        restart: on-failure

        healthcheck:
            test: [ "CMD-SHELL", "curl --silent --fail http://0.0.0.0:6973/ || exit 1" ]
            interval: 5m
            timeout: 3s
            retries: 3

        volumes:
            - ~/AI_web_data/AI/weight/:/weight

        environment:
            DEVICE: "cuda"
            CONFIG_PATH: "/weight/teacher/input_mixed/config.json"
            WEIGHT_PATH: "/weight/teacher/input_mixed/best_epoch12_step2711.pt"
            PORT: 6973

        networks:
            - web

        deploy:
            mode: global
            restart_policy:
                condition: on-failure
                delay: 5s
                window: 120s
                max_attempts: 3
            resources:
                limits:
                    cpus: "8"
                    memory: 8192M
                reservations:
                    cpus: "4"
                    memory: 4096M
                    devices:
                        -   capabilities: [ "gpu" ]
                            device_ids: [ "all" ]

    backend:
        build:
            context: ./Web/src/be
            dockerfile: Dockerfile
            platforms:
                - "linux/amd64"
            tags:
                - "capstone/be:mixed"

        container_name: capstone_be_mixed

        ports:
            - "6974:6974"

        volumes:
            - ~/AI_web_data/BE/input_mixed/run_results/plots:/run_results/plots
            - ~/AI_web_data/BE/input_mixed/run_results/scores:/run_results/scores
            - ~/AI_web_data/BE/input_mixed/run_results/videos:/run_results/videos
        
        environment:
            WINDOW_LENGTH: 15
            POLYORDER: 6

            HEIGHT: 0.75
            THRESHOLD: null
            DISTANCE: null
            PROMINENCE: 0.00001
            WIDTH: 3
            WLEN: null
            REL_HEIGHT: 0.8
            PLATEAU_SIZE: null

            MERGE_GAP: 5

            TMP_DIR: "run_results"
            VAD_ENDPOINT: "http://capstone_ai_mixed:6973"
            PORT: 6974

        restart: on-failure

        healthcheck:
            test: ["CMD", "curl", "-f", "http://0.0.0.0:6974/health"]
            interval: 30s
            timeout: 10s
            retries: 3
            start_period: 15s

        networks:
            - web

        deploy:
            mode: global
            restart_policy:
                condition: on-failure
                delay: 5s
                window: 120s
                max_attempts: 3
            resources:
                limits:
                    cpus: "8"
                    memory: 8192M
                reservations:
                    cpus: "4"
                    memory: 4096M

    frontend:
        build:
            context: ./Web/src/fe
            dockerfile: Dockerfile
            platforms:
                - "linux/amd64"
            tags:
                - "capstone/fe:mixed"

        container_name: capstone_fe_mixed

        ports:
            - "6975:6975"

        environment:
            VITE_API_URL: "http://0.0.0.0:6974/"
            VITE_PORT: 6975

        depends_on:
            - backend

        restart: on-failure

        healthcheck:
            test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://0.0.0.0:6975/"]
            interval: 30s
            timeout: 5s
            retries: 3
            start_period: 5s

        networks:
            - web

        deploy:
            mode: global
            restart_policy:
                condition: on-failure
                delay: 5s
                window: 120s
                max_attempts: 3
            resources:
                limits:
                    cpus: "8"
                    memory: 8192M
                reservations:
                    cpus: "4"
                    memory: 4096M

networks:
  web:
    driver: bridge
