services:
    app:
        build: app
        ports:
            - "6969:6969"
        restart: on-failure
        healthcheck:
            test: [ "CMD-SHELL", "curl --silent --fail localhost:6969/demo_api_2/health-check || exit 1" ]
            interval: 5m
            timeout: 3s
            retries: 3

#    nginx:
#        image: nginx:latest
#        build: nginx
#        restart: always
#        volumes:
#            - ./nginx:/etc/nginx/user_conf.d:ro
#        ports:
#            - "80:80"
#        depends_on:
#            - app
