version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: anomaly-detection-backend
    ports:
      - "8000:8000"
    volumes:
      - ./logs:/var/log/app
      - ./uploads:/home/app/uploads  # Thêm volume cho uploads
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s
    networks:
      - app-network

  frontend:
    build:
      context: ./src/Frontend/v2
      dockerfile: Dockerfile
    container_name: anomaly-detection-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped
    command:

    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:80/"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 5s
    networks:
      - app-network

networks:
  app-network:
    driver: bridge